apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: example-hazelcast
spec:
  size: 3
  config:
    metadata:
      name: hazelcast-configuration
    data:
      hazelcast.yaml: |-
        hazelcast:
          network:
            join:
              multicast:
                enabled: false
              kubernetes:
                enabled: true
                service-name: hazelcast-service
                namespace: default
  service:
    metadata:
      name: hazelcast-service
    spec:
      type: LoadBalancer
      ports:
      - name: hazelcast
        protocol: TCP
        port: 5701