apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: example-hazelcast
spec:
  size: 3
  hostPort: 5701
  config:
    name: hazelcast-configuration
    data:
      hazelcast.yaml: |-
        hazelcast:
          network:
            join:
              multicast:
                enabled: false
              kubernetes:
                enabled: true
                service-name: hazelcast-service
                namespace: default
            rest-api:
              enabled: true
              endpoint-groups:
                HEALTH_CHECK:
                  enabled: true
  service:
    name: hazelcast-service
    type: ClusterIP
    port: 5701
    clusterIP: "None"
