apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: example-hazelcast
spec:
  # Add fields here
  size: 3
  service:
    metadata:
      name: hazelcast-service
    spec:
      type: LoadBalancer
      ports:
      - name: hazelcast
        protocol: TCP
        port: 5701